site/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :comments
  resources :requests
  resources :requests do
    resources :comments
    delete 'destroy_all', on: :collection
  end
  get 'home/about'
  root "home#index"
end

site/app/models/request.rb
class Request < ApplicationRecord
    belongs_to :user

    has_many :comments
    
end

site/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /requests or /requests.json
  def index
    @requests = Request.order(created_at: :desc)
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = current_user.requests.build(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.comments.destroy_all # Видаляємо всі коментарі пов'язані з запитом
    @request.destroy # Видаляємо сам запит
    redirect_to requests_url, notice: "Request and its comments were successfully deleted."
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:category, :first_name, :last_name, :email, :phone, :text_of_request, :user_id)
    end
end

site/app/helpers/requests_helper.rb
module RequestsHelper
end

site/app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="btn-group">
    <%= form.label :category, style: "display: block"%>
  </div>
  <div class="btn-group">
    <%= form.select :category, [['Choose the category', ''],['House', 'House'], ['Food', 'Food'], ['Transportation', 'Transportation'], ['Consulting', 'Consulting'],['Medical services','Medical services'],['Legal services','Legal services']], {}, { class: 'form-control', type: "button", class: "btn btn-info dropdown-toggle wcolor", prompt: 'Choose the category' } %>
  </div>

  <br>
  <br>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name,class:"form-control",placeholder:"Joe" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name,class:"form-control",placeholder:"Biden"%>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email,class:"form-control",placeholder:"example@example.com" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,class:"form-control",placeholder:"012 45 67 891" %>
  </div>

  <div class="form-group">
    <%= form.label :text_of_request, style: "display: block" %>
    <%= form.text_area :text_of_request,class:"form-control",placeholder:"Here you can write about your request" %>
  </div>

  <div class="field form-group">
    <%= form.hidden_field :user_id, id: :request_user_id , class:"form-control-sm"  %>
    
    
  </div>
 


  <br>
  <div>
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>

site/app/views/requests/_request.html.erb
<table id="<%= dom_id request %>" class:='table'>
  <p>
    <strong>Category:</strong>
    <%= request.category %>
  </p>
  
  <p>
    <strong>First name:</strong>
    <%= request.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= request.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= request.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= request.phone %>
  </p>

  <p>
    <strong>Text of request:</strong>
    <%= request.text_of_request %>
  </p>

</table>

site/app/views/requests/edit.html.erb
<body class ="dbody">
<h1>Editing request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Show this request", @request,class:"btn btn-outline-primary" %> |
  <%= link_to "Back to requests", requests_path,class:"btn btn-outline-primary"%>
</div>
</body>

site/app/views/requests/index.html.erb
<body class ="dbody">
<p style="color: green"></p>

<h1>All requests</h1>
<table class="table table-dark table-bordered border-info table-striped ">
  <thead class="table-primary border-success">
    <tr>
      <th scope="col">Category</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Text</th>
      <th scope="col">Show</th>
      <th scope="col">Date of creation</th>
    </tr>
  </thead>

 
  <tbody>
    <div id="requests" >
      <% @requests.each do |request| %>
        <tr>
          <td><%= request.category %></td>
          <td><%= request.first_name %></td>
          <td><%= request.last_name %></td>
          <td><%= request.email %></td>
          <td><%= request.phone %></td>
          <td><%= truncate(request.text_of_request, length: 100, separator: '...') %></td>
          <td>
            <p>
            
              <%= link_to "Show this request", request %>
            
              
            </p></td>
          <td><%= request.created_at %></td>
        </tr>
        
      <% end %>
    </div>
  </tbody>
</table>

<% unless current_user.admin_permit %>
  <%=  link_to "New request", new_request_path, class:"btn btn-primary"  %>
<% end %>
  
</body> 

site/app/views/requests/new.html.erb
<body class ="dbody">
<h1>Create request</h1>

<%= render "form", request: @request %>
<% @request.user_id = current_user.id %>

<br>



<div>
  <%= link_to "Back to requests", requests_path,class:"btn btn-primary" %>
</div>
</body> 

site/app/views/requests/show.html.erb
<body class ="dbody">
<p>
<div class="card">
  <div class="card-header">
    <%=@request.category%>
    
  </div>

    <div class="card-body">
      <br>
      <h5 class="card-title"><%=@request.last_name+' '+@request.first_name%></h5>
      <h5 class="card-title"><%=@request.email+"  "%>|<%="  "+@request.phone%></h5>
      <br>
      <p class="card-text"><%=@request.text_of_request%></p>
      
  
      <br>
      <%if current_user.id== @request.user_id or  current_user.admin_permit%>
        <%= link_to "Edit this request", edit_request_path(@request),class:"btn btn-outline-primary" %>
      |<%end%> 
      <%= link_to "Back to requests", requests_path,class:"btn btn-outline-primary" %>
      <br>
      <br>
      <% if current_user.admin_permit %>
         <%= button_to "Destroy this request", @request,class: "btn btn-danger", method: :delete %>
      <% end %>
  
    </div>
</div>

</p>
<div>


</div>
<%=render "comments/form"%>
</body>