site/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :comments
  resources :requests
  resources :requests do
    resources :comments
    delete 'destroy_all', on: :collection
  end
  get 'home/about'
  root "home#index"
end

site/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    
  end
  
  
end

site/app/helpers/home_helper.rb
module HomeHelper
end

site/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-indigo ">  
  <div class="container-fluid">
   <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "logo" %>
   <% end %>
    <%= link_to 'VaultTec', root_path,class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
          <%= link_to 'Contacts',home_about_path,class:"nav-link"%>
        </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Request',requests_path,class:"nav-link"%>
            </li>
          
            <li class="nav-item">
              <%= link_to 'Add request',new_request_path,class:"nav-link"%>
            </li>  
        <% end %>
        
      </ul>
      <ul class="navbar-nav ">
        <% if user_signed_in? %>
            <li class="nav-button " >

              <%= button_to "Edit profile", edit_user_registration_path, method: :get ,class: "btn btn-warning" %>
              
            </li>

            
            <li class="nav-button " >

              <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
              
            </li>
             

        <% else%>   
            <li class="nav-button " >
            
              <%= button_to 'Log in',new_user_session_path,class: "btn btn-success"%>
            </li>

            <li class="nav-button" >
              
              <%= link_to 'Registration',new_user_registration_path,class: "btn btn-warning"%>
            </li>
          <% end %>

      </ul> 
    </div>
  </div>
</nav>

site/app/views/home/about.html.erb
<body class="body">

<div  style="text-align: left;">
 <div class="card" style="width: 60rem;background-color: #f0f0f0;">
    <div class="card-body">
      <h5 class="card-title" style="font-size: 4em;"> Contacts of Admin</h5>
      <p class="card-text" style="font-size: 20em;">
        <p style="font-size: 2em;" >Email: sasha@gmail.com</p>
        <p style="font-size: 2em;" >Phone: 066 66 66 666</p></p>

  </div>

    
</div> 
</body>

site/app/views/home/index.html.erb
<body class="body">

<div  style="text-align:center; ">
 <div class="card" style="width: 100% background-color: #f0f0f0;  ">
    <div class="card-body">
      <h1 class="card-title"> VaultTec Platform for help</h5>
      <p class="card-text">
        <p>VaultTec is an online platform for volunteer assistance. The site invites volunteers to register and advertise their availability to assist in various projects requiring volunteer labor. Users who need help can create requests on the site, which will be available for viewing by all registered volunteers.

          VaultTec allows you to connect to projects of various sizes - from small community initiatives to large international projects. 
        </p>
        <p>Each volunteer can choose the area of assistance that he or she is interested in or knows best - whether it is volunteering in the field of healthcare, helping children, animals, the environment, culture, etc.

          VaultTec provides a convenient and secure way of communication between volunteers and users who need help.</p>
        <p> The site allows you to monitor the process of work, exchange information, and generally ensures effective coordination of volunteer assistance.

          All in all, VaultTec is a very useful and innovative platform that helps people around the world find those who are willing to provide help and support.</p>
                  
</div> 
</body>