site/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :comments
  resources :requests
  resources :requests do
    resources :comments
    delete 'destroy_all', on: :collection
  end
  get 'home/about'
  root "home#index"
end

site/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :request
  belongs_to :user
end

site/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        
        @request = Request.find(params[:request_id])
        
        @comment = @request.comments.build(comment_params)
        @comment.user = current_user
        if @comment.save
          redirect_to @request, notice: 'Comment was successfully created.'
        else
          render 'requests/show'
        end
      end
     def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
          redirect_to @comment.request
        else
          render 'edit'
        end
      end
      def destroy_all
        @request = Request.find(params[:request_id])
        @request.comments.destroy_all
        redirect_to request_url(@request), notice: "All comments were successfully deleted."
      end
    
     

      def destroy
        @request = Request.find(params[:request_id])
        @comment = @request.comments.find(params[:id])
        @comment.destroy
        redirect_to request_url(@request), notice: "Comment was successfully deleted."
      end

      private

      def comment_params
        params.require(:comment).permit(:body)
      end
end

site/app/helpers/comments_helper.rb
module CommentsHelper
end

site/app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <div>
    
    <h3>Add a Comment:</h3>
    <%= form_with(model: [ @request, @request.comments.build ], url: request_comments_path(@request)) do |form| %>
      <%= form.hidden_field :request_id, value: @request.id %>
      <div class="form-group">
        <%= form.text_area :body, class: "form-control", placeholder: "Your comment..." %>
      </div>
      <br/>
      <%= form.submit "Submit",name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>
<% else %>
  <p>Please <%= link_to "sign in", new_user_session_path %> to add a comment.</p>
<% end %>
<div>
  
  <h3>Comments:</h3>
  
  <% @request.comments.each do |comment| %>
  <%if comment.user%>
    <div class="card">
      <div class="card-header">
        <%= comment.user.name if comment.user %>
      </div>
      <div class="card-body ">
        <p class="card-comnt"><%= comment.body %></p>
      </div>
       <% if current_user.id == comment.user_id || current_user.admin_permit %>
        <%= button_to "Destroy this comment", request_comment_path(@request, comment), method: :delete, class: "btn btn-danger" %>
      <% end %>
      
    </div>
    <%end%>
    <br/>
  <% end %>
  <br/>
</div>